### PR TITLE
 one logo, one vision, one pull request... Just one whole picture.

### PR DESCRIPTION
**Pull request by SebastJava**
@clefebvre  This repository is still waiting. This logo is the very first thing people will see. It is important.

Maybe you were tired of seeing all these issues, and all these PRs? Me too! Sorry but there is something subjective, “artistic” about creating a logo. It takes a single vision. An overall, global vision. I can't do a bunch of little PRs for each pixel that is changed, one by one. That makes things much too heavy and we don't have an overall view this way.

I'm not pushing my own logo here. This logo is not my favorite version. And this color is not my favorite either. I simply took the new logo as approved by you, our project leader, and redesigned and rebuilt everything around it. It's a perfectionist job. Every detail has been looked at.

There should be only one logo, with some variations. For a clear and consistent community image. I am not the only one saying this.

Please don't start analyzing every line of code, just look at the whole picture first:
https://github.com/SebastJava/brand-logo/tree/one#readme

 **one logo, one vision, one pull request...**

### CODE REVIEW

**Comment by SebastJava** [comment]
Now completely re-created. Otherwise, there had been too many re-edits and conversions before. Now there should be no more strange "nn.00001" in node coordinates. This is just perfectionism, in fact the images remain unchanged, identical.

**Comment by SebastJava** [comment]
@clefebvre Allow me to insist once again...

I feel like a painter being asked to do a bunch of small pull requests for each brushstroke to get approved one by one... It doesn't work this way!

This, here, is your logo version, not mine. I only perfected the SVG coding(s). The images are still exactly the same. I checked them all by doing semi-transparent overlays. I also made a better preview and improved the `README.md`.

Everything has been reviewed and corrected in this one big pull request. For the complete story, you could spend hours looking at each commit, but i suggest you just look at the [whole picture](https://github.com/SebastJava/brand-logo/blob/one/README.md).

**one logo, one vision, one pull request...**

**Comment by SebastJava** [comment]
BUMP !

**Comment by clefebvre** [comment]
I get it, I get it :) you got my attention. Thanks Seb, I'll look into it.

**Comment by SebastJava** [comment]
@clefebvre Please wait a few hours.
What a coincidence ! I just happened to use that logo last night. I wanted to change the color. I got this error:
ring-name-mono-green-ERROR
A different line vs fill ! Remember, in order to change the font weight, i simply added some line weight. But now i realize anybody can quickly get into those catastrophic changes when trying to change the color. I just don't want to allow that. I can permanently avoid that in a very simple, fast, secure way: Inkscape menu > Path: Stroke to path, and then union.

I will do this within a few hours from now. Sorry about that. You probably hate to see things getting changed while you are looking at it, but i just can't let this go...

**Comment by SebastJava** [comment]
@clefebvre Update cancelled.  No more commit to wait for. Except for a note to be added in the readme.md. Because i tested this in Inkscape:
* Ungroup
* Convert stroke to path
* Ungroup
* Union

image

▲ Before / After (click to enlarge)

That's still an excellent result. The image is still perfect. Not a single pixel got changed. But looking at the nodes, it just "feels" a bit messy. So, I feel more comfortable in just adding a note in the readme.md about the need to change both lines and fills whenever you want to change the "linuxmint" name to some other color. There is no trouble at all with the "lm" logo itself, but the "linuxmint" name is just a bit tricky, if you want to change its color. But i prefer to leave it as it is. It feels safer.

**Comment by SebastJava** [comment]
@clefebvre "Update cancelled" may sound confusing. This "one" PR here is still **valid**. I just need to add a little note in the readme.md, that's all.

**Comment by SebastJava** [comment]
Done.

**Comment by SebastJava** [comment]
README.md: short and sweet version coming up later tonight...

**Comment by SebastJava** [comment]
### ring-name*.svg made of fill + stroke: my conclusions
Reminder: this stroke of 2.641px width got added to the font converted to path, so the name (i.e.: linuxmint) now has the exact same weight as the logo. My main concern is this is not "fool-proof". Some newbie, willing to change the color, could try to edit these SVGs and make a mistake. But that mistake should be visible, obvious, anyway. Anyway, i had to do my little investigation about possible alternatives.

### Possible alternatives:
* **Inkscape: Ungroup, Path: Convert stroke to path, Ungroup, Path: Union**... the resulting PNG would probably be the exact same thing, but i don't like this method because when looking at the nodes in Inkscape, it feels a bit messy. Sometimes, you get 2 nodes on top of each other. I'd bet that's because they're, like at 0.00000001px from each other. It just feels a bit imperfect, at an atomic level...
* **Inkscape: Path: Path Effects... add (+) Offset and adjust to match the logo's line weight.** This gives a perfect clean result. But then you must save as Inkscape SVG, you can't save as plain SVG. This feels a bit experimental, because i'm not sure if every web browser would handle an Inkscape SVG correctly.
* **Use a variable font.** Ubuntu is not a variable font. But if it was okay to reconsider the font choice, then we could search for some variable font on https://fonts.google.com/ Then, Inkscape: Text > Text and font, use the cursor to adjust weight for a perfect match. Then: Path: Object to Path. This gives perfect results, at first test, at least.

CONCLUSION: I think this "one" PR here is just perfect as it is. But maybe i am just tired and want to see this job finished. But if you insist on exploring new avenues, i could still take the time to do so.

EDIT: Ubuntu IS a variable font according to https://design.ubuntu.com/font

**Comment by SebastJava** [comment]
Still playing around with some logo+name and... I also noticed you have to make sure you have the stroke width auto-scale on when scaling objects in Inkscape. Otherwise the font weight does not match the logo anymore. It isn't "fool proof".

Maybe the second option on previous post would be the best:
**Inkscape: Path: Path Effects... add (+) Offset and adjust to match the logo's line weight.**

I just have to go googling or ask on the forums to make sure saving as Inkscape SVG is okay for all web browsers. But i think it is... **I'm afraid i might have to do some more work...**

**Comment by SebastJava** [comment]
### Full re-edit in progress...
(Same images, but further optimized in the coding.)
* Name created with custom Ubuntu font weight for an exact matching with the logo. Converted to path for portability.
* Logo versions made of one complex path instead of 2 grouped elements where it applies. (i.e.: Using combined paths rather than groups.)
* No more "Save as plain SVG" required. (To be confirmed.)
* Everything will be "fool-proof", thus the "README.md" will be made shorter and easier.

All this will probably be ready within 7 days from now.

**Comment by SebastJava** [comment]
- [x] Name created with custom Ubuntu font weight for an exact matching with the logo. No combination of stroke + path = errors prevented. Text converted to path for portability.
- [x] Logo versions made of one complex path instead of 2 grouped elements where it applies. (i.e.: Using combined paths rather than groups.) Messy translations avoided.
- [x] No more "Save as plain SVG" required. That's just approximately 600 bytes more when saving with the default Inkscape SVG format, and this Inkscape data could be useful.
- [x] Everything is now "fool-proof", thus the "README.md" is now shorter and easier.

All done. :tada:

**Comment by SebastJava** [comment]
That's a monstrously big PR. I will make a presentation that will summarize all this. With an inspection method. I could use Meld to trace all the changes and give a brief description. And explain changes to SVG files, and how to view them in Inkscape, with supporting screenshots.

**Comment by SebastJava** [comment]
# Pull Request "one" summarized

### Story

I was tired of doing a bunch of little pull requests (PR) one-by-one, waiting for one PR to get approved before moving to the next one. And Clem had stopped responding. So, I created this big "one" PR here. One for everything. When i saw Clem seemed to be taking this seriously, i looked at it again and decided to make further changes, more commits.

Now i am trying to summarize all this. Everything got changed ! It is better to look at this PR as something entirely new. For sure, when it comes to examining changes in SVG files, you can't just look at it with some diff tool. One little move can change all the numbers. So, these should be looked in Inkscape, with some description about what was done.

### Summary

Looking at this in Meld (`git difftool -d master..one`), and reading the 50 commits, and the conversation on the PR, i will try to summarize all this...

* Numerous file reclassification and renaming were done. Take a look at those directories. The tests directories could be deleted.
* The source/origin stroke and every other SVG file got RECREATED from scratch. There were too many reedits and I just wanted to restart all this. (Except the leaf versions which got moved into the archives and did not get any reedit.)
* All units are in pixels. Almost everything is made of round numbers. All or almost all variants are of the same size: 256px. The ring and the "Lm" inside share the exact same line width. (This `/usr/share/icons/hicolor/scalable/apps/linuxmint-logo-ring.svg` is not perfect!)
* I replaced all grey (#505050) with pure white (sed -i 's/\#505050/\#ffffff/g' *.svg)
* 2 SVG previews got created in order to see the different logo variants against different backgrounds. They are made of links so they get updated automatically, but they still need to be exported to PNG. That can be done all at once with a simple command, as described in the `README.md`: `cd 90-preview; rm preview*.png; inkscape --export-type=png preview*.svg`
* The `README.md` got reedited many times. At first it was very simple, then it got complex, then it turned short and sweet, as the reedited files do not need any special recommendations.
* New variants got added: `badge-rev.svg` and `ring-rev.svg`.
* `00-archives/high-badge.svg` is now made in a better way. But it got moved into the archives, i.e. reclassified as some "alternate" version...
* The ring and its variants are now made of one single path combining both the ring and the "Lm". Before it was made of 2 grouped elements. Avoiding groups and making this a single path will avoid getting "translate" functions every time those Lm+rings get moved. But this is still not "perfect", as I still had to create groups were those Lm+ring get a solid background, i.e. `ring.svg` and `ring-rev.svg`.
* A lot of time and efforts got invested in recreating the "linuxmint" text for the different ring-name variants. The goal was to get a font weight that would match the "Lm" thickness, without adding any stroke to it. The result is 4 ring-name variants were no stroke is being used, just plain filled paths. This will avoid any mistake when scaling or changing the color. See commit ce74be8e7d4178a8a4bf7052df36904be1b1338a for full details. In other words, it is now "FOOLPROOF".
* The files are now saved as Inkscape SVG. That's less trouble and it avoids loosing some potentially valuable data. Using this default Inkscape save format, all the SVG files got a transparent 10% grey page color. This way you won't get confused when you open some 100% white mono variant, as you can still see something when opened in Inkscape. And this page color doesn't affect anything else but the way things are displayed in Inkscape. Otherwise it is still just a transparent background.

**...And please remember,** there is no new design here, as already said in this PR's OP. The different logo variants are exactly the same images as before, and the ring-name variants are still the same too, with an approximate ± 1 pixel accuracy. All this is just about making a perfect SVG source code. For every single file, which makes a lot. And a better README with better previews. And some reclassification. That's it, that's all :)

P.S.: No new design... except for this new https://github.com/SebastJava/brand-logo/tree/one/70-new-fonts-and-colors

### Screenshots

**Before**, on master branch, the name was made of a fill + stroke combination:
ring-name-added-stroke-on-font-screenshot

**After**, on this "one" branch, the name is made of a variable Ubuntu font now converted to path:
ring-name-Ubuntu-var-font-weight-screenshot
(No more fill + stroke combination, and the nodes are all clean ! Thanks to a custom variable Ubuntu font.)

**Comment by SebastJava** [comment]
@clefebvre This PR can probably be considered stable now. All done. All summarized in this [previous post right here](https://github.com/linuxmint/brand-logo/pull/19#issuecomment-1419887757).

As already said, this is only about technical perfection. Except this https://github.com/SebastJava/brand-logo/tree/one/70-new-fonts-and-colors new experiment.

**Pull request closed without merging**
