### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by Secret-chest**
This is a new version of the Linux Mint logo.
It looks like this:

Before closing this, keep in mint that the LM is the same. If you think it's hard to change the logo, you may let me do it because for me it's easy and we could have the same logo on the new website (website-wizixo), blog, forums, and community.
People seem to like it. Look: https://forums.linuxmint.com/viewtopic.php?f=19&t=355555
I only got positive comments and some say you should consider switching over to this.
### The reasoning
I made this logo because the new circle shape does not look minty at all, the logo is lacking in depth, has too many variants, etcetera. While the old logo is too complicated, it appears offcenter due to the stem, etcetera.
Please consider switching over to this. It's not really that hard. :)

### CODE REVIEW

**Comment by SebastJava** [comment]
I agree this logo has "too many variants". It should be one company, one logo.

IdrisTheDragon was saying this too:
> I think 3 the Simple, Ring and Filled badge ones would be plenty.
> edit: actually 4 variants including one with text "linuxmint" style.
> ye should probably either stick with the leaf or get rid of it, not both, adds confusion to the branding.

And yes, "the old logo is too complicated, it appears offcenter due to the stem, etcetera."
Etcetera! There are many wrong things with the old logo from 2007.

Personally, I think i prefer the "high-badge" one. With some new colour. But at least I agree that this new "leaf" version is much better than the old version from 2007.

high-badge-256

**Comment by Secret-chest** [comment]
> I agree this logo has \"too many variants\". It should be one company, one logo.

Well Linux Mint is not a company, but yes. Why can't we just have the normal, monochrome, outline, and simple/base logos?

**Comment by Secret-chest** [comment]
> > I agree this logo has \"too many variants\". It should be one company, one logo.
> 
> Well Linux Mint is not a company, but yes. Why can't we just have the normal, monochrome, outline, and simple/base logos?

By the way the other 3 logos should be only used when needed

**Comment by Secret-chest** [comment]
> Personally, I think i prefer the \"high-badge\" one. With some new colour. But at least I agree that this new \"leaf\" version is much better than the old version from 2007

I used this leaf shape to make the logo look more minty

**Comment by Secret-chest** [comment]
> Personally, I think i prefer the \"high-badge\" one. With some new colour. But at least I agree that this new \"leaf\" version is much better than the old version from 2007

I used this leaf shape to make the logo look more minty.

**Comment by SebastJava** [comment]
I prefer my colour: #00b894. It comes from there: https://flatuicolors.com/palette/us. It is called Mint Leaf. Because the mint colour is something around this 168° hue. The current official brand colour is... #86BE43. I don't like it. That is a greyish-yellow-green. Yes, colour is supposed to be a separate topic, but i find it hard to "sell" something with such a bad colour.

I would prefer to see your logo version with my colour: #00b894. Or maybe some kind of gradient ?

**Comment by Secret-chest** [comment]
> I prefer my colour: #00B894. It comes from there: https://flatuicolors.com/palette/us. It is called Mint Leaf. Because the mint colour is something around this 168° hue. The current official brand colour is... #86BE43. I don't like it. That is a greyish-yellow-green. Yes, colour is supposed to be a separate topic, but i find it hard to "sell" something with such a bad colour.
> 
> I would prefer to see your logo version with my colour: #00B894. Or maybe some kind of gradient ?

Well, your color is too electric. I chose this color because it looks natural and relaxing.
Gradients would be a big no from me, that was one of the problems with the old logo.

**Comment by SebastJava** [comment]
Hey, looking at your new logo here made me wake up to old memories. I had tried something similar back in year 2018. You can still find it there: https://forums.linuxmint.com/viewtopic.php?f=19&t=280401

And i still have some ideas i never took the time to make. 99% of the things i do gets rejected anyway. And being perfectionist, everything i do takes a big amount of time. So, i didn't want to waste my time. But, looking at your things, i got this little extra motivation to try something else, one more time.

Here: https://github.com/SebastJava/brand-logo/tree/leaf


leaf-2

**Comment by Secret-chest** [comment]
> Hey, looking at your new logo here made me wake up to old memories. I had tried something similar back in year 2018. You can still find it there: https://forums.linuxmint.com/viewtopic.php?f=19&t=280401
> 
> And i still have some ideas i never took the time to make. 99% of the things i do gets rejected anyway. And being perfectionist, everything i do takes a big amount of time. So, i didn't want to waste my time. But, looking at your things, i got this little extra motivation to try something else, one more time.
> 
> Here: https://github.com/SebastJava/brand-logo/tree/leaf
> 
> 
> leaf-2
> 

I do not think the LM shape should be changed. Sorry, but that angle looks very bad.
If the logo shape would be a leaf, then we should drop the high badge idea.

**Comment by Secret-chest** [comment]
I know my green is a lot less cyan, but I have seen mint IRL...

**Comment by SebastJava** [comment]
> Well, your color is too electric.

That's right. I shouldn't use "electric" colours. Electricity and electronics have nothing to do with computers. :)

**Comment by Secret-chest** [comment]
> > Well, your color is too electric.
> 
> That's right. I shouldn't use "electric" colours. Electricity and electronics have nothing to do with computers. :)

Lol. But the idea is that Linux Mint is meant to have a calm nature.

**Comment by Secret-chest** [comment]
@clefebvre

**Comment by clefebvre** [comment]
Please don't change the logo. This project isn't about exploring new alternatives.

**Pull request closed without merging**
